name: Docker Pipeline

on:
  push:
    branches:
      - feature/docker-setup
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/DockerLab:latest .
      
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/DockerLab:latest

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/DockerLab:latest
      
      - name: Run tests
        run: docker run ${{ secrets.DOCKER_USERNAME }}/DockerLab:latest python -m unittest discover -s tests
