name: Docker Image

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GIT_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GIT_USERNAME }}" --password-stdin

      - name: Build Main Docker image
        run: docker build . --tag ghcr.io/${{ secrets.GIT_USERNAME }}/docker-modprog:latest

      - name: Push Main Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.GIT_USERNAME }}/docker-modprog:latest

      - name: Build Test Docker image
        run: docker build -t ghcr.io/${{ secrets.GIT_USERNAME }}/docker-modprog:test -f Dockerfile.test .

      - name: Push Test Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.GIT_USERNAME }}/docker-modprog:test

      - name: Run tests in Docker container
        run: docker run ghcr.io/${{ secrets.GIT_USERNAME }}/docker-modprog:test
